version: '3'

volumes:
  postgres_volume_local:
  postgres_volume_prod:

services:
  pg:
    image: postgres:15-alpine3.18
    env_file:
      - ".env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg
